### ISSUE TITLE
Feature Request: disable functions

### ISSUE THREAD

**Issue by tjorim** [grocy/grocy#157]
Would be nice if a user could disable things that won't be used to clutter the UI less.
E.g., we don't have any rechargeable batteries or chores that need to be managed.

**Comment by berrnd** [comment]
Are `config.php` options needed for this or is maybe some [custom CSS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) enough?

E. g. hide the two mentioned menu elements with:
```css
[data-nav-for-page="batteriesoverview"],
[data-nav-for-page="choresoverview"] {
	display: none;
}
```
