### ISSUE TITLE
Feature request: Floating Save buttons on product edit/create page

### ISSUE THREAD

**Issue by xionous** [grocy/grocy#1589]
Would it be possible to have the product edit/create page have a floating footer with the save buttons in it so you don't always have to scroll to the very bottom to save?

**Comment by b1n4ryj4n** [comment]
Hi i assume its pretty easy to implement like this:
![2021-09-04 13-29-25](https://user-images.githubusercontent.com/3122325/132093273-3e886170-1f60-41c9-9bb2-4c2531210d86.gif)

for quick solution you can add `<div class="product-form-footer">` before
https://github.com/grocy/grocy/blob/14bb04d285a3c04508f4ba8b837a1de805fd2c34/views/productform.blade.php#L494
and `</div>` before
https://github.com/grocy/grocy/blob/14bb04d285a3c04508f4ba8b837a1de805fd2c34/views/productform.blade.php#L502

and the css you need is something like this
```css
form#product-form .form-group:nth-last-child(2) {
	padding-bottom: 4rem;
}
form#product-form .product-form-footer {
	background-color: white;
	border-top: 1px solid #000;
	bottom: 0;
	padding: 0;
	position: fixed;
	width: 50%;
	z-index: 5000;
}
```
