### ISSUE TITLE
Add support for fractions throughout

### ISSUE THREAD

**Issue by DeeeeLAN** [grocy/grocy#389]
This is a great package:
https://github.com/infusion/Fraction.js/

Not sure if it would be feasible, but this would be really nice to have.

**Comment by berrnd** [comment]
If it's about displaying numbers, that's already possible in plain JS, also already used in many places, but not all, like:

https://github.com/grocy/grocy/blob/c5927a10f3a682cfa917ff845e4c3191dc471e85/public/js/grocy.js#L516-L532

If it comes to how the numbers are stored in the database, that would be totally different as currently all number are stored as integers or decimals and AFAIK there is not SQL datatype (above all not in SQLite) which handles fractions itself...

**Comment by DeeeeLAN** [comment]
Partially it is to make the numbers display nicer, but it would also be nicer for adding and consuming amounts, it would make a lot of it more even. I know that the package I linked stores the numerator and denominator as two separate integers, so I imagine that would be a good way to manage it in a database. You could just store whole numbers as #/1.

**Comment by berrnd** [comment]
> I know that the package I linked stores the numerator and denominator as two separate integers

Yeah, I think that's the only possible way...
But that would make a big change how amounts are calculated on every place...
I give this a very low priority for now...

Personally I try to keep it as simple as simple, so don't track any partial amounts at all, means most of the time I only track a product once when it's used completely, not when it's partially used. In first place I was against all partial amount stuff ([ref](https://github.com/grocy/grocy/issues/123), [ref](https://github.com/grocy/grocy/issues/105), [ref](https://github.com/grocy/grocy/issues/32#issuecomment-408946222)), but obviously I were convinced enought to add it though... :D

> Partially it is to make the numbers display nicer

That I already tried to address in https://github.com/grocy/grocy/commit/21503c26d2f1eb44377056ac8035e0f91892d4fa (but not using fractions, only browser-locale-specific proper formatted decimal numbers).

**Comment by DeeeeLAN** [comment]
Yeah that makes sense, definitely just a "nice to have" type thing, not a major issue. I would definitely be all for only tracking complete amounts, but that is tricky with recipes somewhat. I guess anything that uses a partial amount I would just not track stock, that would work. I might play around with that. 

Maybe if I want it enough I will look at adding this eventually. It is definitely a big shift like you said, so I would want to understand the code-base better first.

**Comment by checketts** [comment]
With this feature not happening. Here is a silly hack that makes the stock `consume` a bit more firendly 

If you put this in a file in `data/custom_css.html`
```css
<style>
.product-consume-button[data-consume-amount="0.1"] .locale-number.locale-number-quantity-amount::after {
  content: " (1/10)";
}

.product-consume-button[data-consume-amount="0.5"] .locale-number.locale-number-quantity-amount::after {
  content: " (1/2)";
}

.product-consume-button[data-consume-amount="0.33"] .locale-number.locale-number-quantity-amount::after {
  content: " (1/3)";
}

.product-consume-button[data-consume-amount="0.25"] .locale-number.locale-number-quantity-amount::after {
  content: " (1/4)";
}

.product-consume-button[data-consume-amount="0.2"] .locale-number.locale-number-quantity-amount::after {
  content: " (1/5)";
}

.product-consume-button[data-consume-amount="0.16"] .locale-number.locale-number-quantity-amount::after {
  content: " (1/6)";
}

.product-consume-button[data-consume-amount="0.125"] .locale-number.locale-number-quantity-amount::after {
  content: " (1/8)";
}

.product-consume-button[data-consume-amount="0.05"] .locale-number.locale-number-quantity-amount::after {
  content: " (1/20)";
}

.product-consume-button[data-consume-amount="0.03"] .locale-number.locale-number-quantity-amount::after {
  content: " (1/20)";
}

.product-consume-button[data-consume-amount="0.01"] .locale-number.locale-number-quantity-amount::after {
  content: " (1/100)";
}
</style>
```

Then for common fractions it will change `0.25` to `0.25 (1/4)`
<img width="392" alt="image" src="https://github.com/grocy/grocy/assets/416063/1a667f82-aec7-4b21-ad66-ccb317a3ff00">


It is just a hack, but kind of useful.
