### ISSUE TITLE
Unable to Purchase when best before date tracked

### ISSUE THREAD

**Issue by zsarnett** [grocy/grocy#742]
I am having an issue where on the purchase screen I am unable to click OK when trying to purchase a product. I have the product filled in and the amount but OK is disabled.

![image](https://user-images.githubusercontent.com/18730868/79476527-14b00e80-7fd7-11ea-983d-1678d3505c8b.png)

I am running Grocery on HASS.IO with the following config.

### Config - 
```yaml
culture: en
currency: USD
entry_page: calendar
features:
  batteries: false
  calendar: true
  chores: true
  equipment: false
  recipes: true
  shoppinglist: true
  stock: true
  tasks: false
tweaks:
  chores_assignment: true
  multiple_shopping_lists: false
  stock_best_before_date_tracking: false
  stock_location_tracking: false
  stock_price_tracking: false
  stock_product_freezing: false
  stock_product_opened_tracking: false
```

If I change `stock_best_before_date_tracking` to `true` the best by date field appears and I am able to choose a date and click OK
